In [1]:
import numpy as np
a = np.random.randint(1,100,15)
print(a)
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[78 35 39 56  4 49 60 62 25 18 33 32 15 46 23]
[[36 77 53 83]
 [53 18 56 14]
 [27 24 34 94]
 [15 45 89  1]
 [14 47 36 99]
 [ 9 28 43 42]]


### np.sort

In [2]:
# Return the copy of sorted array
np.sort(a)             #array([10, 23, 26, 34, 41, 43, 48, 54, 54, 63, 77, 80, 89, 96, 99],dtype=int32)
np.sort(a)[::-1]       #to sort in descending order
np.sort(b,axis=1)      #sorts the element in row-wise #np.sort(b,axis=1)  
np.sort(b,axis=0)      #column-wise sorting

array([[ 9, 18, 34,  1],
       [14, 24, 36, 14],
       [15, 28, 43, 42],
       [27, 45, 53, 83],
       [36, 47, 56, 94],
       [53, 77, 89, 99]], dtype=int32)

### np.append

In [3]:
#adds the element at the end of array
np.append(a,200)    #array([ 77,  54,  10,  54,  43,  99,  34,  26,  96,  23,  41,  48,  80, 63,  89, 200])

np.append(b,np.ones((b.shape[0],1)),axis=1)
'''array([[43., 89., 16., 77.,  1.],
       [93., 13.,  8., 90.,  1.],
       [13., 11., 19., 85.,  1.],
       [33., 28., 93., 33.,  1.],
       [73., 35.,  9.,  9.,  1.],
       [22., 72., 23.,  7.,  1.]])'''

'array([[43., 89., 16., 77.,  1.],\n       [93., 13.,  8., 90.,  1.],\n       [13., 11., 19., 85.,  1.],\n       [33., 28., 93., 33.,  1.],\n       [73., 35.,  9.,  9.,  1.],\n       [22., 72., 23.,  7.,  1.]])'

### np.concatenate

In [4]:
#concatenate a sequence of array along an exixting axis
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

np.concatenate((c,d),axis=0)
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

In [5]:
#we can get the unique values from an array given as parameter in np.unique() method
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

np.unique(e)    #array([1, 2, 3, 4, 5, 6])
np.unique(f)    #array([1, 2, 3])

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


array([1, 2, 3])

### np.expand_dims

In [6]:
#we can get the expanded dimension of an array
np.expand_dims(a,axis=0)          #array([[86, 59,  9, 74, 70,  1, 35, 77, 70, 31, 71, 47, 92, 62, 17]],dtype=int32)
np.expand_dims(a,axis=1)
np.expand_dims(a,axis=1).shape    #(15, 1) gives the dimension of the array

(15, 1)

### np.where

In [7]:
#returns the indices of the elements in an input array where the given conditionis satisfied
#find all indices with value greater than 50
print(a)
np.where(a > 50)

#replace all value > 50 with 0
#SYNTAX : np.where(condition,true,false)
np.where(a>50,0,a)

#replace even number to zero
np.where(a%2==0,0,a)

[78 35 39 56  4 49 60 62 25 18 33 32 15 46 23]


array([ 0, 35, 39,  0,  0, 49,  0,  0, 25,  0, 33,  0, 15,  0, 23],
      dtype=int32)

### np.argmax/np.argmin

In [8]:
#return the indices of the max/min element of the array in particular axis
np.argmax(a)
np.argmin(a)

#2D
print(b)
np.argmax(b,axis=0)
np.argmin(b,axis=1)

[[36 77 53 83]
 [53 18 56 14]
 [27 24 34 94]
 [15 45 89  1]
 [14 47 36 99]
 [ 9 28 43 42]]


array([0, 3, 1, 3, 0, 0])

### np.cumsum

In [9]:
#used when we want to compute the cumulative sum of array elements over a given axis
print(a)
np.cumsum(a)    #array([ 86, 145, 154, 228, 298, 299, 334, 411, 481, 512, 583, 630, 722,784, 801])

#2d
np.cumsum(b,axis=0)

[78 35 39 56  4 49 60 62 25 18 33 32 15 46 23]


array([[ 36,  77,  53,  83],
       [ 89,  95, 109,  97],
       [116, 119, 143, 191],
       [131, 164, 232, 192],
       [145, 211, 268, 291],
       [154, 239, 311, 333]])

### np.cumprod

In [10]:
# cumalitive product
np.cumprod(a)

array([                  78,                 2730,               106470,
                    5962320,             23849280,           1168614720,
                70116883200,        4347246758400,      108681168960000,
           1956261041280000,    64556614362240000,  2065811659591680000,
       -5906313253543903232,  5010751442623725568,  4566818738088378368])

### np.percentile

In [ ]:
# Used to compute the nth percentile of the given data(array elements)along the specified axis
np.percentile(a,100)      #np.float64(78.0)
np.percentile(a,50)       #np.float64(35.0)

np.float64(35.0)

### np.histogram

In [14]:
# represent the ferquency of data distribution in the given graphical form
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 2, 4, 2, 1, 2, 1, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

### np.corrcoef

In [16]:
#Return Pearson product-moment correlation coefficients.
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

In [19]:
'''With the help of numpy.isin() method, we can see that one array having values are checked in a 
different numpy array having different elements with different sizes.'''
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([60], dtype=int32)

### np.flip

In [25]:
'''The numpy.flip() function reverses the order of array elements along the specified axis,
 preserving the shape of the array.'''
print(a)
np.flip(a)


#2D
print(b)
np.flip(b,axis=0)
np.flip(b,axis=1)

[78 35 39 56  4 49 60 62 25 18 33 32 15 46 23]
[[36 77 53 83]
 [53 18 56 14]
 [27 24 34 94]
 [15 45 89  1]
 [14 47 36 99]
 [ 9 28 43 42]]


array([[83, 53, 77, 36],
       [14, 56, 18, 53],
       [94, 34, 24, 27],
       [ 1, 89, 45, 15],
       [99, 36, 47, 14],
       [42, 43, 28,  9]], dtype=int32)

### np.put

In [ ]:
'''The numpy.put() function replaces specific elements of an array with given values of p_array. 
 Array indexed works on flattened array.''' 
print(a)
np.put(a,[0,1],[77,34])     #np.put(a,[index],[items])
print(a)

[78 35 39 56  4 49 60 62 25 18 33 32 15 46 23]
[77 34 39 56  4 49 60 62 25 18 33 32 15 46 23]


### np.delete

In [31]:
#The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis
print(a)
np.delete(a,2)

#delete multiple item
np.delete(a,[1,2,3])

[77 34 39 56  4 49 60 62 25 18 33 32 15 46 23]


array([77,  4, 49, 60, 62, 25, 18, 33, 32, 15, 46, 23], dtype=int32)

### Set functions
np.union1d

np.intersect1d

np.setdiff1d

np.setxor1d

np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

#union
np.union1d(m,n)     #array([1, 2, 3, 4, 5, 6, 7])

#intersection
np.intersect1d(m,n)     #array([3, 4, 5])

#sei-difference
np.setdiff1d(m,n)      #array([1, 2])
np.setdiff1d(n,m)      #array([6, 7])

#xor(remove the intersection)
np.setxor1d(m,n)       #array([1, 2, 6, 7])

#in1d(check if item is present or not)
#np.in1d(m,n)
#m[np.in1d(m,1)]

array([3, 4, 5])

### np.clip

In [40]:
#numpy.clip() function is used to Clip (limit) the values in an array.
print(a)
np.clip(a,a_min=25,a_max=75)

[77 34 39 56  4 49 60 62 25 18 33 32 15 46 23]


array([75, 34, 39, 56, 25, 49, 60, 62, 25, 25, 33, 32, 25, 46, 25],
      dtype=int32)

### np.swapaxes

In [ ]:
#

### np.uniform

In [ ]:
#

### np.count_nonzero

In [ ]:
#

### np.tile

In [ ]:
## https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

### np.repeat

In [ ]:
#

### np.allclose and equals