### Creating NumPy Array(1-3)

In [ ]:
#Creating numpy array(VECTOR)
import numpy as np
a = np.array([1,2,3])
print(a)

In [ ]:
#2D array(MATRIX)
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D array(TENSOR)
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#To find data types
np.array([1,2,3],dtype=bool) #(True/False)
np.array([1,2,3],dtype=float) #(Float)
np.array([1,2,3],dtype=complex) #(Complex Number)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#(start,stop)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#(start,stop,step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#reshaping the array  reshape(row,column) OR reshape(row,column)
#rows x colunm = no.of items present in array

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Initialization Techniques

#### 1.

In [ ]:
#all items in array are one
#SYNTAX: np.ones(row,column)
#where we use this? To initialize arrays
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 2.

In [ ]:
#all items in array are zero
#SYNTAX: np.zeros(row,column)
#where we use this? To initialize arrays
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 3.

In [ ]:
#give random numbers between 0-1 in an array
#where we use this? To initialize arrays
np.random.random((3,4))

array([[0.93247756, 0.62057785, 0.20233173, 0.99451403],
       [0.00291251, 0.83331841, 0.99262819, 0.32135695],
       [0.56322754, 0.79670173, 0.82417004, 0.15735295]])

### Creating NumPy Array(4-5)

In [ ]:
#linspace: linearly seperable
#SYNTAX: np.linspace(lower value , higher value , no.of item)
#generates the point at equal distance(linearly seperably) among give item
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#generates the identity matrix
#SYNTAX: np.identity()
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
#generated an array for further functions
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#to find dimension of array
a1.ndim    #1
a2.ndim    #2
a3.ndim    #3

3

In [ ]:
#To find the structure of array
a1.shape #(10,)
a2.shape #(3, 4)
a3.shape #(2, 2, 2)

(2, 2, 2)

In [ ]:
#To find number of items
a1.size    #10      
a2.size    #12
a3.size    #8

8

In [ ]:
#It gives how much size each item takes in memory
#integer 32 takes 4 bytes
#integer 64 takes 8 bytes
a1.itemsize    #8(bytes)
a2.itemsize    #8(bytes) 
a3.itemsize    #8(bytes)

8

In [ ]:
#to find data types of items in array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


### Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)     
a2 



array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### Scalar Operation 

In [ ]:
# +,-,*,/
a1 * 2
a2 ** 2
a2 + 3

array([[15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

#### Relational Operation

In [ ]:
# ==,< , > ,<= , >= 
a1 == 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

#### Vector Operations

In [ ]:
a1+a2
a1**a2
a1*a2
a1/a2
a1**a2
a1//a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Array Function

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 55., 15.],
       [14., 57., 27.],
       [11.,  5., 91.]])

In [ ]:
# min / max /sum / product
np.max(a1)    #85.0
np.min(a1)    #10.0
np.sum(a1)    #414.0
np.prod(a1)   #90028924876800.0

#row and column wise operation
#all operations are allowed min / max /sum / product
#0 ->column      1->row
np.max(a1,axis=1)    #array([68., 85., 69.])
np.max(a1,axis=0)

array([33., 57., 91.])

In [ ]:
# mean / median / standard deviation / variance
np.mean(a1)                #46.0
np.mean(a1,axis=0)         #array([46.66666667, 36.        , 55.33333333])
np.median(a1)              #57.0
np.median(a1,axis=1)       #array([64., 57., 13.])
np.std(a1)                 #np.float64(26.940263134902334)
np.std(a1,axis=0)          #array([23.61261433, 22.09072203, 30.72819914])
np.var(a1)                 #np.float64(725.7777777777778)
np.var(a1,axis=1)          #array([603.55555556, 434.88888889, 736.22222222])

array([ 267.55555556,  324.22222222, 1536.88888889])

In [ ]:
# trignometric function
np.sin(a1)

array([[ 0.99991186, -0.99975517,  0.65028784],
       [ 0.99060736,  0.43616476,  0.95637593],
       [-0.99999021, -0.95892427,  0.10598751]])

In [ ]:
# dot product
#Here No.of R1 = No. of R2
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents
np.log(a1)
np.exp(a1)

array([[2.14643580e+14, 7.69478527e+23, 3.26901737e+06],
       [1.20260428e+06, 5.68572000e+24, 5.32048241e+11],
       [5.98741417e+04, 1.48413159e+02, 3.31740010e+39]])

In [ ]:
# round : round off the nereast integer
# floor : eg. 6.5->6  
# ceil  : eg. 6.1->7
np.round(np.random.random((2,2))*100)
np.floor(np.random.random((2,2))*100)
np.ceil(np.random.random((2,2))*100)

array([[31., 82.],
       [20., 98.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#indexing for 1D array
a1[-1]

np.int64(9)

In [ ]:
#indexing for 2D array  a2[row,column]
a2[1,2]

np.int64(6)

In [ ]:
#indexing for 3D array   a3[array,row,column]
a3[1,0,1]

np.int64(5)

In [ ]:
#slicing   1D array
a1[2:5]
a1[::-1]  # reversing an array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#slicing 2D array
a2[0,:]  #first row
a2[:,2]
a2[1:,1:3]
a2[::2,::3]
a2[0::2,1::2]   #a2[::2,1::2]
a2[1,::3]
a2[:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#slicing 3D array
a3[1]          #selecting 2d array
a3[::2]        #alternate 2d array
a3[0,1]        #first 2d array and second array
a3[1,::,1]     #second 2d array and second column
a3[2,1:,1:]  
a3[::2,0,::2]   

array([[ 0,  2],
       [18, 20]])

### Iterating

In [ ]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
#iterate each element in array
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
#Changes the row of matrix to column and column to row
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
#changes any dimension array to 1D array
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
# Horizontal Stacking
np.hstack((a4,a5))
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# Vertical Stacking
# Used when? when there are multiple data sources
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# Horizontal splitting(has to ve equal division)
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting
#used when we have to make multiple things from one data dource
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]